#!/usr/bin/env bats
# shellcheck disable=SC2030,SC2031 # Each Bats test receives setup variables in its own subshell.

setup() {
    COMPOSE="$BATS_TEST_DIRNAME/../bin/minios-image-compose"
    STUBS="$BATS_TEST_DIRNAME/stubs"
    SYSTEM_PATH=$PATH
    TEST_ROOT="$BATS_TEST_TMPDIR/job $BATS_TEST_NUMBER"
    SOURCE="$TEST_ROOT/source tree = [x]\\root"
    CONFIG="$TEST_ROOT/config files/live config.conf"
    MANIFEST="$TEST_ROOT/manifests/build manifest.json"
    OUTPUT_DIR="$TEST_ROOT/output dir"
    OUTPUT="$OUTPUT_DIR/image partial.iso"
    STATE="$TEST_ROOT/xorriso state"
    TEMP_ROOT="$TEST_ROOT/tmp"
    CAPTURE_STUB="$TEST_ROOT/capture bin/savechanges"
    CAPTURE_STATE="$TEST_ROOT/savechanges state"
    PKEXEC_STUB="$TEST_ROOT/capture bin/pkexec"
    PKEXEC_STATE="$TEST_ROOT/pkexec state"
    TOOL_EUID_LOG="$TEST_ROOT/tool-euids.log"
    SESSION_SELECTION="$TEST_ROOT/session selection.json"
    OVERLAY_MKS_STUB="$TEST_ROOT/capture bin/mksquashfs"

    mkdir -p \
        "$SOURCE/boot/syslinux" \
        "$SOURCE/boot/grub/i386-pc" \
        "$SOURCE/boot/EFI/BOOT" \
        "$SOURCE/empty target" \
        "$SOURCE/modules" \
        "${CONFIG%/*}" \
        "${MANIFEST%/*}" \
        "$OUTPUT_DIR" \
        "$STATE" \
        "$CAPTURE_STATE" \
        "$PKEXEC_STATE" \
        "$TEMP_ROOT" \
        "${CAPTURE_STUB%/*}"

    write_file "$SOURCE/boot/syslinux/isolinux.bin" isolinux
    write_file "$SOURCE/boot/syslinux/isohdpfx.bin" isohybrid
    write_file "$SOURCE/boot/syslinux/syslinux.cfg" syslinux-config
    write_file "$SOURCE/boot/grub/efi.img" efi
    write_file "$SOURCE/boot/grub/grub.cfg" grub-config
    write_file "$SOURCE/boot/vmlinuz-test" kernel
    write_file "$SOURCE/boot/initrfs-test.img" initramfs
    write_file "$SOURCE/boot/EFI/BOOT/BOOTX64.EFI" efi-loader
    write_file "$SOURCE/00-core-amd64.sb" core-module
    write_file "$SOURCE/01-kernel-amd64.sb" kernel-module
    write_file "$CONFIG" configuration
    write_file "$MANIFEST" '{"schema_version":1}'
    cp "$STUBS/savechanges" "$CAPTURE_STUB"
    cp "$STUBS/pkexec" "$PKEXEC_STUB"
    cp "$STUBS/mksquashfs" "$OVERLAY_MKS_STUB"
    chmod 0755 "$CAPTURE_STUB" "$PKEXEC_STUB" "$OVERLAY_MKS_STUB"
    ln -s vmlinuz-test "$SOURCE/boot/kernel-link"
    ln -s '../empty target' "$SOURCE/boot/empty-directory-link"
}

write_file() {
    local path=$1
    shift
    mkdir -p "${path%/*}"
    printf '%s\n' "$*" >"$path"
}

prepare_custom_boot_fixture() {
    mkdir -p "$SOURCE/boot/syslinux/lang"
    write_file "$SOURCE/boot/grub/grub.cfg" $'set default=0\nset timeout=10\nmenuentry "English" {\n  configfile /minios/boot/grub/main.cfg\n}'
    write_file "$SOURCE/boot/grub/main.cfg" $'set default=0\nset timeout=10\nmenuentry "Translated resume" --class resume {\n  linux /minios/boot/vmlinuz-test boot=live quiet perchdir=resume\n}\nmenuentry "Translated new" --class new {\n  linux /minios/boot/vmlinuz-test boot=live quiet perchdir=new\n}\nmenuentry "Translated choose" --class switch {\n  linux /minios/boot/vmlinuz-test boot=live quiet perchdir=ask\n}\nmenuentry "Translated fresh" --class live {\n  linux /minios/boot/vmlinuz-test boot=live quiet\n}\nmenuentry "Translated RAM" --class ram {\n  linux /minios/boot/vmlinuz-test boot=live quiet toram\n}'
    write_file "$SOURCE/boot/syslinux/syslinux.cfg" $'PROMPT 0\nTIMEOUT 100\nLABEL en_US\nMENU LABEL English\nCONFIG lang/en_US.cfg\nLABEL ru_RU\nMENU LABEL Russian\nCONFIG lang/ru_RU.cfg'
    write_file "$SOURCE/boot/syslinux/lang/en_US.cfg" $'TIMEOUT 100\nONTIMEOUT default\nLABEL default\nMENU DEFAULT\nMENU LABEL Translated resume\nKERNEL /minios/boot/vmlinuz-test\nAPPEND boot=live quiet perchdir=resume\nLABEL perch\nMENU LABEL Translated new\nKERNEL /minios/boot/vmlinuz-test\nAPPEND boot=live quiet perchdir=new\nLABEL asksession\nMENU LABEL Translated choose\nKERNEL /minios/boot/vmlinuz-test\nAPPEND boot=live quiet perchdir=ask\nLABEL live\nMENU LABEL Translated fresh\nKERNEL /minios/boot/vmlinuz-test\nAPPEND boot=live quiet\nLABEL toram\nMENU LABEL Translated RAM\nKERNEL /minios/boot/vmlinuz-test\nAPPEND boot=live quiet toram'
    cp "$SOURCE/boot/syslinux/lang/en_US.cfg" "$SOURCE/boot/syslinux/lang/ru_RU.cfg"
}

prepare_syslinux_grub_fixture() {
    prepare_custom_boot_fixture
    write_file "$SOURCE/boot/grub/i386-pc/lnxboot.img" lnxboot
    write_file "$SOURCE/boot/grub/i386-pc/core.img" core
    # Generated by linux-live/minioslib for BOOTLOADER=syslinux-grub.
    write_file "$SOURCE/boot/syslinux/syslinux.cfg" $'PROMPT 0\nTIMEOUT 1\n\nDEFAULT grub2\n\nLABEL grub2\nMENU LABEL GRUB2\nLINUX /minios/boot/grub/i386-pc/lnxboot.img\nINITRD /minios/boot/grub/i386-pc/core.img'
}

create_test_png() {
    local output=$1
    local width=${2:-800}
    local height=${3:-600}
    python3 -c '
import struct, sys, zlib
width, height = int(sys.argv[2]), int(sys.argv[3])
def chunk(kind, payload):
    body = kind + payload
    return struct.pack(">I", len(payload)) + body + struct.pack(">I", zlib.crc32(body) & 0xffffffff)
ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
scanlines = b"".join(b"\0" + b"\0" * (width * 3) for _ in range(height))
data = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(scanlines)) + chunk(b"IEND", b"")
open(sys.argv[1], "wb").write(data)
' "$output" "$width" "$height"
}

prepare_real_iso_fixture() {
    REAL_XORRISO=$(PATH="$SYSTEM_PATH" command -v xorriso) || skip 'xorriso is not installed'
    REAL_MKSQUASHFS=$(PATH="$SYSTEM_PATH" command -v mksquashfs) || skip 'mksquashfs is not installed'
    PATH="$SYSTEM_PATH" command -v unsquashfs >/dev/null || skip 'unsquashfs is not installed'
    PATH="$SYSTEM_PATH" command -v mkfs.ext2 >/dev/null || skip 'mkfs.ext2 is not installed'

    rm -f "$SOURCE/00-core-amd64.sb" "$SOURCE/01-kernel-amd64.sb"
    module_root="$TEST_ROOT/real module root"
    mkdir -p "$module_root/core" "$module_root/kernel"
    write_file "$module_root/core/core.txt" core
    write_file "$module_root/kernel/kernel.txt" kernel
    "$REAL_MKSQUASHFS" "$module_root/core" "$SOURCE/00-core-amd64.sb" \
        -noappend -all-root -quiet
    "$REAL_MKSQUASHFS" "$module_root/kernel" "$SOURCE/01-kernel-amd64.sb" \
        -noappend -all-root -quiet

    python3 -c '
import os, sys
for relative, size in (("boot/syslinux/isolinux.bin", 4096),
                       ("boot/syslinux/isohdpfx.bin", 432),
                       ("boot/grub/efi.img", 1024 * 1024)):
    with open(os.path.join(sys.argv[1], relative), "wb") as stream:
        stream.write(b"\0" * size)
' "$SOURCE"
    write_file "$SOURCE/boot/syslinux/syslinux.cfg" $'PROMPT 0\nTIMEOUT 10\nDEFAULT live\nLABEL live\nKERNEL /minios/boot/vmlinuz-test\nAPPEND initrd=/minios/boot/initrfs-test.img boot=live'
    write_file "$SOURCE/boot/grub/grub.cfg" $'set default=0\nset timeout=10\nmenuentry "Fresh" --class live {\n  linux /minios/boot/vmlinuz-test boot=live\n  initrd /minios/boot/initrfs-test.img\n}'

    mkdir -p "$SOURCE/metadata"
    write_file "$SOURCE/metadata/executable" executable
    write_file "$SOURCE/metadata/plain" plain
    chmod 0755 "$SOURCE/metadata/executable"
    chmod 0644 "$SOURCE/metadata/plain"
    ln -s plain "$SOURCE/metadata/plain-link"
    truncate -s 17825792 "$SOURCE/metadata/large.bin"
    chmod 0644 "$SOURCE/metadata/large.bin"
    touch -d '@1700000000' "$SOURCE/metadata/executable" "$SOURCE/metadata/plain" \
        "$SOURCE/metadata/plain-link" "$SOURCE/metadata/large.bin"

    REAL_XORRISO_TOOLS="$TEST_ROOT/real xorriso tools"
    REAL_XORRISO_STATE="$TEST_ROOT/real xorriso state"
    mkdir -p "$REAL_XORRISO_TOOLS" "$REAL_XORRISO_STATE"
    cp "$STUBS/xorriso-real-wrapper" "$REAL_XORRISO_TOOLS/xorriso"
    chmod 0755 "$REAL_XORRISO_TOOLS/xorriso"
}

assert_process_gone() {
    local process_id=$1
    for _ in {1..100}; do
        kill -0 "$process_id" 2>/dev/null || return 0
        sleep 0.05
    done
    kill -KILL "$process_id" 2>/dev/null || true
    return 1
}

run_compose() {
    run env \
        PATH="$STUBS:$SYSTEM_PATH" \
        TMPDIR="$TEMP_ROOT" \
        XORRISO_STATE="$STATE" \
        XORRISO_BUILD_MODE="${XORRISO_BUILD_MODE:-success}" \
        XORRISO_OMIT_DEST="${XORRISO_OMIT_DEST:-}" \
        XORRISO_TAMPER_EXTRACT="${XORRISO_TAMPER_EXTRACT:-}" \
        XORRISO_MUTATE_GRAFT="${XORRISO_MUTATE_GRAFT:-}" \
        XORRISO_RACE_INPUT="${XORRISO_RACE_INPUT:-}" \
        XORRISO_RACE_INPUT_PARENT="${XORRISO_RACE_INPUT_PARENT:-}" \
        XORRISO_RACE_INPUT_VICTIM="${XORRISO_RACE_INPUT_VICTIM:-}" \
        XORRISO_RACE_OUTPUT_TARGET="${XORRISO_RACE_OUTPUT_TARGET:-}" \
        XORRISO_RACE_OUTPUT_PARENT="${XORRISO_RACE_OUTPUT_PARENT:-}" \
        XORRISO_RACE_OUTPUT_VICTIM="${XORRISO_RACE_OUTPUT_VICTIM:-}" \
        MKFS_EXT2_FAIL="${MKFS_EXT2_FAIL:-false}" \
        MKSQUASHFS_STATE="${MKSQUASHFS_STATE:-}" \
        MKSQUASHFS_SLEEP="${MKSQUASHFS_SLEEP:-false}" \
        MKSQUASHFS_SLEEP_MARKER="${MKSQUASHFS_SLEEP_MARKER:-}" \
        MKSQUASHFS_STUBBORN="${MKSQUASHFS_STUBBORN:-false}" \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 \
        MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        MINIOS_TOOLS_TEST_MOUNTINFO="${MINIOS_TOOLS_TEST_MOUNTINFO:-}" \
        MINIOS_TOOLS_TEST_CMDLINE="${MINIOS_TOOLS_TEST_CMDLINE:-}" \
        MINIOS_TOOLS_TEST_BOOT_ID="${MINIOS_TOOLS_TEST_BOOT_ID:-}" \
        MINIOS_TOOLS_TEST_RUNNING_SOURCE="${MINIOS_TOOLS_TEST_RUNNING_SOURCE:-}" \
        MINIOS_TOOLS_TEST_MKSQUASHFS="${MINIOS_TOOLS_TEST_MKSQUASHFS:-}" \
        MINIOS_TOOLS_TEST_UNSQUASHFS="${MINIOS_TOOLS_TEST_UNSQUASHFS:-}" \
        COMPOSE_TEST_SAVECHANGES="$CAPTURE_STUB" \
        COMPOSE_TEST_PKEXEC="$PKEXEC_STUB" \
        COMPOSE_TEST_CHANGES_ROOT="${COMPOSE_TEST_CHANGES_ROOT:-}" \
        COMPOSE_TEST_MKSQUASHFS="${COMPOSE_TEST_MKSQUASHFS:-$OVERLAY_MKS_STUB}" \
        COMPOSE_TEST_OVERLAY_PAUSE="${COMPOSE_TEST_OVERLAY_PAUSE:-}" \
        PKEXEC_STUB_STATE="$PKEXEC_STATE" \
        PKEXEC_STUB_ROOT="${PKEXEC_STUB_ROOT:-false}" \
        SAVECHANGES_STUB_STATE="$CAPTURE_STATE" \
        SAVECHANGES_STUB_MODE="${SAVECHANGES_STUB_MODE:-success}" \
        SAVECHANGES_STUB_METADATA_MODE="${SAVECHANGES_STUB_METADATA_MODE:-valid}" \
        SAVECHANGES_STUB_VERSION="${SAVECHANGES_STUB_VERSION:-1.3.0}" \
        SAVECHANGES_STUB_SOURCE="$SOURCE" \
        SAVECHANGES_STUB_BASE_FINGERPRINT="${SAVECHANGES_STUB_BASE_FINGERPRINT:-}" \
        UNSQUASHFS_FAIL_PATTERN="${UNSQUASHFS_FAIL_PATTERN:-__never__}" \
        UNSQUASHFS_TAMPER_TREE="${UNSQUASHFS_TAMPER_TREE:-}" \
        TOOL_EUID_LOG="$TOOL_EUID_LOG" \
        NO_COLOR=1 \
        "$COMPOSE" \
        --source "$SOURCE" \
        --config "$CONFIG" \
        --name "$OUTPUT" \
        "$@"
}

start_overlay_compose() {
    local log=$1
    shift
    (
        cd "$TEST_ROOT" || exit 1
        exec env \
            PATH="$STUBS:$SYSTEM_PATH" \
            TMPDIR="$TEMP_ROOT" \
            XORRISO_STATE="$STATE" \
            MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 \
            MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
            COMPOSE_TEST_MKSQUASHFS="$OVERLAY_MKS_STUB" \
            COMPOSE_TEST_OVERLAY_PAUSE="${COMPOSE_TEST_OVERLAY_PAUSE:-}" \
            MKSQUASHFS_STATE="${MKSQUASHFS_STATE:-}" \
            MKSQUASHFS_SLEEP="${MKSQUASHFS_SLEEP:-false}" \
            MKSQUASHFS_SLEEP_MARKER="${MKSQUASHFS_SLEEP_MARKER:-}" \
            MKSQUASHFS_STUBBORN="${MKSQUASHFS_STUBBORN:-false}" \
            TOOL_EUID_LOG="$TOOL_EUID_LOG" \
            NO_COLOR=1 \
            "$COMPOSE" --source "$SOURCE" --config "$CONFIG" --name "$OUTPUT" "$@"
    ) >"$log" 2>&1 &
    STARTED_COMPOSE_PID=$!
}

assert_capture_arg_pair() {
    local option=$1
    local expected=$2
    local -a arguments
    local index

    mapfile -d '' -t arguments <"$CAPTURE_STATE/args"
    for index in "${!arguments[@]}"; do
        if [[ ${arguments[$index]} == "$option" ]]; then
            [[ ${arguments[$((index + 1))]} == "$expected" ]]
            return
        fi
    done
    return 1
}

assert_output_contains() {
    [[ $output == *"$1"* ]]
}

assert_build_arg_pair() {
    local option=$1
    local expected=$2
    local -a arguments
    local index

    mapfile -d '' -t arguments <"$STATE/build.args"
    for index in "${!arguments[@]}"; do
        if [[ ${arguments[$index]} == "$option" ]]; then
            [[ ${arguments[$((index + 1))]} == "$expected" ]]
            return
        fi
    done
    return 1
}

@test "explicit source config manifest and volume label reach xorriso" {
    write_file "$SOURCE/config.conf" source-private-configuration
    chmod 000 "$SOURCE/config.conf"
    run_compose --manifest "$MANIFEST" --volume-label "MINIOS LAB" --no-color

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    [[ $output != *'P:customize'* ]]
    [ "$(grep -Fc '/minios/image-customization.json' "$STATE/tree")" -eq 0 ]
    assert_build_arg_pair -volid "MINIOS LAB"
    grep -Fqx '/minios/config.conf' "$STATE/tree"
    grep -Fqx '/minios/build-manifest.json' "$STATE/tree"
    grep -Fqx '/minios/boot/kernel-link' "$STATE/tree"
    grep -Fqx '/minios/boot/empty-directory-link' "$STATE/tree"
    grep -Fqx '/minios/empty target' "$STATE/tree"
    mapfile -d '' -t graft_values <"$STATE/graft-sources"
    config_snapshot=""
    for ((index = 0; index < ${#graft_values[@]}; index += 2)); do
        if [[ ${graft_values[$index]} == minios/config.conf ]]; then
            config_snapshot=${graft_values[$((index + 1))]}
        fi
    done
    [[ $config_snapshot != */input-snapshots/* ]]
    [ "$config_snapshot" -ef "$CONFIG" ]
    [ "$(<"$STATE/config.conf")" = configuration ]
    [ ! -e "$SOURCE/boot/vmlinuz" ]
    [ ! -e "$SOURCE/boot/initrfs.img" ]
    [ "$(<"$SOURCE/boot/syslinux/isolinux.bin")" = isolinux ]
}

@test "long option equals forms parse and an explicit empty name is rejected" {
    equals_output="$OUTPUT_DIR/equals.iso"
    run env PATH="$STUBS:$SYSTEM_PATH" TMPDIR="$TEMP_ROOT" \
        XORRISO_STATE="$STATE" NO_COLOR=1 \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        "$COMPOSE" "--source=$SOURCE" "--config=$CONFIG" \
        "--manifest=$MANIFEST" '--volume-label=MINIOS' \
        "--name=$equals_output"
    [ "$status" -eq 0 ]
    [ -s "$equals_output" ]

    run env PATH="$STUBS:$SYSTEM_PATH" TMPDIR="$TEMP_ROOT" \
        XORRISO_STATE="$STATE" NO_COLOR=1 \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        "$COMPOSE" "--source=$SOURCE" "--config=$CONFIG" '--name='
    [ "$status" -ne 0 ]
    assert_output_contains 'Invalid output filename'
}

@test "an existing source manifest is preserved without an explicit manifest" {
    write_file "$SOURCE/build-manifest.json" '{"from":"source"}'

    run_compose

    [ "$status" -eq 0 ]
    grep -Fqx '/minios/build-manifest.json' "$STATE/tree"
}

@test "top-level source modules do not require an empty modules directory" {
    rmdir "$SOURCE/modules"

    run_compose

    [ "$status" -eq 0 ]
    grep -Fqx '/minios/00-core-amd64.sb' "$STATE/tree"
    grep -Fqx '/minios/01-kernel-amd64.sb' "$STATE/tree"
}

@test "graft argv preserves spaces equals backslashes globs tabs and leading dashes" {
    odd_relative=$'data dir/-odd [x]*=\\name\tfile.txt'
    write_file "$SOURCE/$odd_relative" odd-data
    module="$TEST_ROOT/additional modules/addon.sb"
    write_file "$module" addon

    run_compose "$module"

    [ "$status" -eq 0 ]
    grep -Fqx "/minios/$odd_relative" "$STATE/tree"
    grep -Fqx '/minios/modules/addon.sb' "$STATE/tree"
    [ -e "$STATE/sources.ok" ]
}

@test "source names with newlines fail explicit preflight" {
    newline_path=$'data/new\nline'
    write_file "$SOURCE/$newline_path" unsafe

    run_compose

    [ "$status" -ne 0 ]
    assert_output_contains 'must not contain newline characters'
    [ ! -e "$OUTPUT" ]
}

@test "additional module cannot collide with an included source module" {
    write_file "$SOURCE/modules/addon.sb" source-addon
    module="$TEST_ROOT/other/addon.sb"
    write_file "$module" other-addon

    run_compose "$module"

    [ "$status" -ne 0 ]
    assert_output_contains 'destination collides'
    [ ! -e "$OUTPUT" ]
}

@test "flattened source module basenames are unique for no-custom overlay and capture builds" {
    write_file "$SOURCE/duplicate.sb" top-level
    write_file "$SOURCE/modules/duplicate.sb" modules-directory
    overlay="$TEST_ROOT/duplicate overlay"
    mkdir "$overlay"
    write_file "$overlay/value" overlay

    run_compose
    [ "$status" -ne 0 ]
    assert_output_contains 'Duplicate module basename after runtime flattening'
    [ ! -e "$OUTPUT" ]

    pushd "$TEST_ROOT" >/dev/null
    run_compose --overlay-directory "$overlay"
    popd >/dev/null
    [ "$status" -ne 0 ]
    assert_output_contains 'Duplicate module basename after runtime flattening'
    [ ! -e "$OUTPUT" ]

    run_compose --capture-changes exact
    [ "$status" -ne 0 ]
    assert_output_contains 'Duplicate module basename after runtime flattening'
    [ ! -e "$OUTPUT" ]
}

@test "invalid additional SquashFS is rejected with diagnostics" {
    module="$TEST_ROOT/modules/invalid.sb"
    write_file "$module" invalid

    run_compose "$module"

    [ "$status" -eq 3 ]
    assert_output_contains 'invalid SquashFS image'
    assert_output_contains 'not valid SquashFS'
    [ ! -e "$OUTPUT" ]
}

@test "existing output is preserved unless overwrite is explicit" {
    write_file "$OUTPUT" original-output

    run_compose
    [ "$status" -ne 0 ]
    [ "$(<"$OUTPUT")" = original-output ]

    run_compose --overwrite
    [ "$status" -eq 0 ]
    [ "$(<"$OUTPUT")" = 'partial ISO' ]
}

@test "required boot module config and manifest exclusions fail preflight" {
    local pattern
    local expected
    local -a patterns=(
        '^boot/vmlinuz'
        '^00-core'
        '(^|/)config[.]conf$'
        'build-manifest[.]json$'
    )
    local -a messages=(
        'excluded path'
        'required source module'
        'minios/config.conf'
        'minios/build-manifest.json'
    )

    for index in "${!patterns[@]}"; do
        pattern=${patterns[$index]}
        expected=${messages[$index]}
        run_compose --manifest "$MANIFEST" --exclude "$pattern"
        [ "$status" -ne 0 ]
        assert_output_contains "$expected"
        [ ! -e "$OUTPUT" ]
    done
}

@test "source symlink chains reject an excluded immediate component" {
    mkdir -p "$SOURCE/links"
    write_file "$SOURCE/links/final" final
    ln -s final "$SOURCE/links/intermediate"
    ln -s intermediate "$SOURCE/links/top"

    run_compose --exclude '^links/intermediate$'

    [ "$status" -ne 0 ]
    assert_output_contains 'chain contains an excluded path'
    [ ! -e "$OUTPUT" ]
}

@test "configuration and source arguments reject final symlinks" {
    config_link="$TEST_ROOT/config-link.conf"
    source_link="$TEST_ROOT/source-link"
    ln -s "$CONFIG" "$config_link"
    ln -s "$SOURCE" "$source_link"

    run env PATH="$STUBS:$SYSTEM_PATH" XORRISO_STATE="$STATE" TMPDIR="$TEMP_ROOT" \
        "$COMPOSE" --source "$SOURCE" --config "$config_link" --name "$OUTPUT"
    [ "$status" -ne 0 ]
    assert_output_contains 'must not be a symbolic link'

    run env PATH="$STUBS:$SYSTEM_PATH" XORRISO_STATE="$STATE" TMPDIR="$TEMP_ROOT" \
        "$COMPOSE" --source "$source_link" --config "$CONFIG" --name "$OUTPUT"
    [ "$status" -eq 2 ]
    assert_output_contains 'must not be a symbolic link'
}

@test "invalid labels and invalid JSON manifests fail before output work" {
    run_compose --volume-label $'BAD\nLABEL'
    [ "$status" -ne 0 ]
    assert_output_contains 'printable ASCII'

    write_file "$MANIFEST" '{not-json'
    run_compose --manifest "$MANIFEST"
    [ "$status" -ne 0 ]
    assert_output_contains 'Manifest is not valid JSON'
    [ ! -e "$OUTPUT" ]
}

@test "isolated adapter helpers ignore malicious Python modules in the working directory" {
    poison="$TEST_ROOT/poison modules"
    marker="$TEST_ROOT/poison-executed"
    mkdir -p "$poison"
    for module in ctypes hashlib json; do
        printf 'open("%s", "a").write("%s\\n")\n' "$marker" "$module" >"$poison/$module.py"
    done

    original_directory=$PWD
    cd "$poison"
    run_compose
    cd "$original_directory"

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    [ ! -e "$marker" ]
}

@test "writer and structural verification failures remove the exact target" {
    MKFS_EXT2_FAIL=true run_compose
    [ "$status" -ne 0 ]
    assert_output_contains 'requested failure'
    assert_output_contains 'Failed to format persistence image'
    [ ! -e "$OUTPUT" ]

    MKFS_EXT2_FAIL=false
    XORRISO_BUILD_MODE=fail run_compose
    [ "$status" -ne 0 ]
    assert_output_contains 'requested write failure'
    [ ! -e "$OUTPUT" ]

    XORRISO_BUILD_MODE=success
    XORRISO_OMIT_DEST=minios/config.conf run_compose
    [ "$status" -ne 0 ]
    assert_output_contains 'missing grafted path: minios/config.conf'
    [ ! -e "$OUTPUT" ]
}

@test "input and output identity races fail without overwriting attacker paths" {
    config_parent=${CONFIG%/*}
    input_victim="$TEST_ROOT/input ancestor victim"
    write_file "$input_victim/live config.conf" attacker-config

    XORRISO_RACE_INPUT_PARENT="$config_parent" \
        XORRISO_RACE_INPUT_VICTIM="$input_victim" run_compose
    [ "$status" -ne 0 ]
    assert_output_contains 'changed during ISO creation'
    [ ! -e "$OUTPUT" ]
    [ "$(<"$STATE/config.conf")" = configuration ]
    rm -- "$config_parent"
    mv -- "$config_parent.moved" "$config_parent"

    XORRISO_RACE_INPUT="$CONFIG" run_compose
    [ "$status" -ne 0 ]
    assert_output_contains 'changed during ISO creation'
    [ ! -e "$OUTPUT" ]
    [ "$(<"$STATE/config.conf")" = configuration ]
    write_file "$CONFIG" configuration

    XORRISO_RACE_OUTPUT_TARGET="$OUTPUT" run_compose
    [ "$status" -ne 0 ]
    assert_output_contains 'output path identity changed'
    [ "$(<"$OUTPUT")" = 'attacker output' ]
    rm -- "$OUTPUT"

    output_victim="$TEST_ROOT/output ancestor victim"
    mkdir -p "$output_victim"
    write_file "$output_victim/sentinel" untouched
    XORRISO_RACE_OUTPUT_PARENT="$OUTPUT_DIR" \
        XORRISO_RACE_OUTPUT_VICTIM="$output_victim" run_compose
    [ "$status" -ne 0 ]
    assert_output_contains 'output path identity changed'
    [ "$(<"$output_victim/sentinel")" = untouched ]
    [ ! -e "$output_victim/image partial.iso" ]
    [ ! -e "$OUTPUT_DIR.moved/image partial.iso" ]
    shopt -s nullglob
    private_outputs=("$OUTPUT_DIR.moved"/.minios-image-compose-output.*)
    [ "${#private_outputs[@]}" -eq 0 ]
}

@test "successful output includes stable phase IDs" {
    run_compose

    [ "$status" -eq 0 ]
    for phase_id in prepare boot-copy persistence iso-write verify complete; do
        assert_output_contains "P:$phase_id"
    done
    [[ $output != *$'\e['* ]]
}

@test "capture option combinations validate before build work" {
    run_compose --capture-changes selected
    [ "$status" -ne 0 ]
    assert_output_contains 'requires --capture-selection'

    write_file "$SESSION_SELECTION" '{"product_kind":"minios-session-selection","schema_version":1,"include_paths":[],"exclude_paths":[]}'
    run_compose --capture-changes clean --capture-selection "$SESSION_SELECTION"
    [ "$status" -ne 0 ]
    assert_output_contains 'only valid with --capture-changes selected'

    run_compose --capture-compression xz
    [ "$status" -ne 0 ]
    assert_output_contains 'requires --capture-changes'

    run_compose --capture-changes=unsafe
    [ "$status" -ne 0 ]
    assert_output_contains 'Invalid session capture mode'

    run_compose --capture-changes=
    [ "$status" -ne 0 ]
    assert_output_contains 'Invalid session capture mode'

    run_compose --capture-changes clean --capture-compression=unsafe
    [ "$status" -ne 0 ]
    assert_output_contains 'Invalid session capture compression'
    [ ! -e "$OUTPUT" ]
}

@test "capture requires the exact-fidelity savechanges contract version" {
    SAVECHANGES_STUB_VERSION=1.2.9 run_compose --capture-changes exact

    [ "$status" -ne 0 ]
    assert_output_contains 'savechanges 1.3.0 or newer is required for capture'
    [ ! -e "$OUTPUT" ]
}

@test "capture accepts nested unnumbered modules in boot sort order" {
    write_file "$SOURCE/modules/group/addon.sb" addon

    run_compose --capture-changes exact

    [ "$status" -eq 0 ]
    grep -Fqx '/minios/modules/group/addon.sb' "$STATE/tree"
    [ -s "$STATE/session-capture.json" ]
}

@test "boot customization follows multilingual session configs and ignores translated labels" {
    prepare_custom_boot_fixture
    background="$TEST_ROOT/custom background.png"
    create_test_png "$background" 1024 768
    cp "$background" "$SOURCE/boot/bootlogo788.png"
    kernel_text='audit=1 customization_token=redacted'
    expected_kernel_hash=$(printf '%s' "$kernel_text" | sha256sum)
    expected_kernel_hash=${expected_kernel_hash%% *}

    run_compose --boot-timeout=7 --default-boot choose \
        --kernel-args "$kernel_text" --boot-background "$background"

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    assert_output_contains 'P:customize'
    [[ $output != *"$kernel_text"* ]]
    [[ $(<"$STATE/files/minios/boot/grub/grub.cfg") == *'set timeout=7'* ]]
    [[ $(<"$STATE/files/minios/boot/grub/grub.cfg") == *'set default=0'* ]]
    grep -Fqx 'set default=2' "$STATE/files/minios/boot/grub/main.cfg"
    grep -Fqx 'set timeout=7' "$STATE/files/minios/boot/grub/main.cfg"
    [ "$(grep -Fc " $kernel_text" "$STATE/files/minios/boot/grub/main.cfg")" -eq 5 ]
    grep -Fqx 'TIMEOUT 70' "$STATE/files/minios/boot/syslinux/syslinux.cfg"
    [ "$(grep -Ec '^DEFAULT ' "$STATE/files/minios/boot/syslinux/syslinux.cfg")" -eq 0 ]
    for language in en_US ru_RU; do
        config="$STATE/files/minios/boot/syslinux/lang/$language.cfg"
        grep -Fqx 'DEFAULT asksession' "$config"
        grep -Fqx 'ONTIMEOUT asksession' "$config"
        [ "$(grep -Fc 'MENU DEFAULT' "$config")" -eq 0 ]
        grep -Fqx 'TIMEOUT 70' "$config"
        [ "$(grep -Fc " $kernel_text" "$config")" -eq 5 ]
    done
    cmp -s "$background" "$STATE/files/minios/boot/bootlogo788.png"
    cmp -s "$background" "$STATE/files/minios/boot/bootlogo791.png"
    [[ $(<"$SOURCE/boot/grub/main.cfg") != *"$kernel_text"* ]]

    run python3 -c '
import json, sys
report = json.load(open(sys.argv[1], encoding="utf-8"))
assert report["product_kind"] == "minios-image-customization"
assert report["schema_version"] == 1
assert report["boot"]["timeout_seconds"] == 7
assert report["boot"]["default_boot"] == "choose"
assert report["boot"]["kernel_args"] == {"bytes": len(sys.argv[2].encode()), "sha256": sys.argv[3]}
assert len(report["boot"]["configs"]) == 5
assert report["boot"]["background"]["width"] == 1024
assert report["boot"]["background"]["height"] == 768
assert set(report["boot"]["background"]["targets"]) == {
    "minios/boot/bootlogo788.png", "minios/boot/bootlogo791.png"}
assert report["overlay"] is None
assert sys.argv[2] not in open(sys.argv[1], encoding="utf-8").read()
' "$STATE/image-customization.json" "$kernel_text" "$expected_kernel_hash"
    [ "$status" -eq 0 ]
}

@test "localized generated GRUB config receives semantic default and timeout customization" {
    prepare_custom_boot_fixture
    mkdir -p "$SOURCE/boot/grub/po"
    cp "$SOURCE/boot/grub/main.cfg" "$SOURCE/boot/grub/grub.template.cfg"
    write_file "$SOURCE/boot/grub/po/de_DE.po" $'msgid "MiniOS"\nmsgstr "MiniOS Deutsch"'

    run_compose --menu de_DE --boot-timeout 0 --default-boot toram

    [ "$status" -eq 0 ]
    grep -Fqx 'set timeout=0' "$STATE/files/minios/boot/grub/grub.cfg"
    grep -Fqx 'set default=4' "$STATE/files/minios/boot/grub/grub.cfg"
    [[ $(<"$STATE/files/minios/boot/grub/grub.cfg") == *'locales=de_DE.UTF-8'* ]]
}

@test "all supported default boot modes map to GRUB classes and SYSLINUX semantics" {
    prepare_custom_boot_fixture
    local index mode expected_index expected_label
    local -a modes=(resume new choose fresh toram)
    local -a indexes=(0 1 2 3 4)
    local -a labels=(default perch asksession live toram)
    for index in "${!modes[@]}"; do
        mode=${modes[$index]}
        expected_index=${indexes[$index]}
        expected_label=${labels[$index]}
        run_compose --default-boot "$mode"
        [ "$status" -eq 0 ]
        grep -Fqx "set default=$expected_index" "$STATE/files/minios/boot/grub/main.cfg"
        grep -Fqx "DEFAULT $expected_label" "$STATE/files/minios/boot/syslinux/lang/en_US.cfg"
        rm "$OUTPUT"
    done
}

@test "MiniOS SYSLINUX-GRUB chainloader delegates session customization to GRUB" {
    prepare_syslinux_grub_fixture
    kernel_text='audit=1 chainloader=verified'

    run_compose --boot-timeout 4 --default-boot fresh --kernel-args "$kernel_text"

    [ "$status" -eq 0 ]
    grep -Fqx 'set timeout=4' "$STATE/files/minios/boot/grub/main.cfg"
    grep -Fqx 'set default=3' "$STATE/files/minios/boot/grub/main.cfg"
    [ "$(grep -Fc " $kernel_text" "$STATE/files/minios/boot/grub/main.cfg")" -eq 5 ]
    grep -Fqx 'TIMEOUT 1' "$STATE/files/minios/boot/syslinux/syslinux.cfg"
    grep -Fqx 'LINUX /minios/boot/grub/i386-pc/lnxboot.img' \
        "$STATE/files/minios/boot/syslinux/syslinux.cfg"
    [ "$(grep -Fc "$kernel_text" "$STATE/files/minios/boot/syslinux/syslinux.cfg")" -eq 0 ]
    run python3 -c '
import json, sys
report = json.load(open(sys.argv[1], encoding="utf-8"))
assert {item["target"] for item in report["boot"]["configs"]} == {
    "minios/boot/grub/grub.cfg", "minios/boot/grub/main.cfg"}
' "$STATE/image-customization.json"
    [ "$status" -eq 0 ]
}

@test "MiniOS SYSLINUX-GRUB chainloader rejects every extra boot directive" {
    prepare_syslinux_grub_fixture
    chainloader=$(<"$SOURCE/boot/syslinux/syslinux.cfg")
    local directive
    local -a directives=(
        'COM32 menu.c32'
        'LOCALBOOT 0'
        'BOOT /minios/boot/vmlinuz-test'
        'KERNEL /minios/boot/vmlinuz-test'
        'APPEND boot=live'
        'LINUX /minios/boot/vmlinuz-test'
        'INITRD /minios/boot/initrfs-test.img'
    )

    for directive in "${directives[@]}"; do
        printf '%s\n%s\n' "$chainloader" "$directive" >"$SOURCE/boot/syslinux/syslinux.cfg"
        run_compose --boot-timeout 4
        [ "$status" -ne 0 ]
        assert_output_contains 'not a provable GRUB chainloader'
        [ ! -e "$OUTPUT" ]
    done
}

@test "native SYSLINUX without a provable session menu remains ambiguous" {
    prepare_custom_boot_fixture
    write_file "$SOURCE/boot/syslinux/syslinux.cfg" $'PROMPT 0\nDEFAULT grub2\nLABEL grub2\nLINUX /minios/boot/grub/i386-pc/lnxboot.img\nINITRD /minios/boot/grub/i386-pc/core.img'

    run_compose --default-boot fresh

    [ "$status" -ne 0 ]
    assert_output_contains 'cannot represent the requested customization'
    [ ! -e "$OUTPUT" ]
}

@test "image customization options reject unsafe and out-of-range values" {
    local value
    for value in -1 301 1.5 ''; do
        run_compose "--boot-timeout=$value"
        [ "$status" -ne 0 ]
        assert_output_contains 'Boot timeout must be an integer from 0 to 300'
        [ ! -e "$OUTPUT" ]
    done

    run_compose --default-boot translated-label
    [ "$status" -ne 0 ]
    assert_output_contains 'Invalid default boot mode'

    for value in $'quiet\tdebug' $'quiet\ndebug' "name=\$unsafe" 'foo="bar"'; do
        run_compose --kernel-args "$value"
        [ "$status" -ne 0 ]
        [[ $output != *"$value"* ]]
        [ ! -e "$OUTPUT" ]
    done

    oversized=$(printf 'a%.0s' {1..4097})
    run_compose --kernel-args "$oversized"
    [ "$status" -ne 0 ]
    assert_output_contains 'exceed 4096'
    [ ! -e "$OUTPUT" ]

    run_compose --overlay-directory "$TEST_ROOT"
    [ "$status" -ne 0 ]
    assert_output_contains 'must not contain the MiniOS source tree'

    run_compose --overlay-directory ./relative-overlay
    [ "$status" -ne 0 ]
    assert_output_contains 'must be an absolute path'
}

@test "default session customization fails when an active menu lacks semantic proof" {
    prepare_custom_boot_fixture
    write_file "$SOURCE/boot/grub/main.cfg" $'set default=0\nset timeout=10\nmenuentry "Translated mystery" {\n  linux /minios/boot/vmlinuz-test root=/dev/ram0 quiet\n}'

    run_compose --default-boot toram

    [ "$status" -ne 0 ]
    assert_output_contains 'cannot represent the requested customization'
    [ ! -e "$OUTPUT" ]

    write_file "$SOURCE/boot/grub/main.cfg" $'set default=0\nsubmenu "Sessions" {\nmenuentry "Resume" --class resume {\n  linux /minios/boot/vmlinuz-test boot=live perchdir=resume\n}\n}'
    run_compose --default-boot resume
    [ "$status" -ne 0 ]
    assert_output_contains 'cannot represent the requested customization'
    [ ! -e "$OUTPUT" ]
}

@test "boot background rejects symlink invalid dimensions oversized and tampered PNG data" {
    invalid="$TEST_ROOT/not-a-png.png"
    write_file "$invalid" invalid
    run_compose --boot-background "$invalid"
    [ "$status" -ne 0 ]
    assert_output_contains 'not a supported PNG'

    dimensions="$TEST_ROOT/invalid dimensions.png"
    create_test_png "$dimensions" 9000 600
    run_compose --boot-background "$dimensions"
    [ "$status" -ne 0 ]
    assert_output_contains 'not a supported PNG'

    oversized="$TEST_ROOT/oversized.png"
    create_test_png "$oversized"
    truncate -s 16777217 "$oversized"
    run_compose --boot-background "$oversized"
    [ "$status" -ne 0 ]
    assert_output_contains 'not a supported PNG'

    valid="$TEST_ROOT/valid.png"
    create_test_png "$valid"

    bad_crc="$TEST_ROOT/bad crc.png"
    cp "$valid" "$bad_crc"
    python3 -c 'import sys
path = sys.argv[1]
data = bytearray(open(path, "rb").read())
data[-1] ^= 1
open(path, "wb").write(data)' "$bad_crc"
    run_compose --boot-background "$bad_crc"
    [ "$status" -ne 0 ]
    assert_output_contains 'not a supported PNG'

    trailing="$TEST_ROOT/trailing.png"
    cp "$valid" "$trailing"
    printf unsafe >>"$trailing"
    run_compose --boot-background "$trailing"
    [ "$status" -ne 0 ]
    assert_output_contains 'not a supported PNG'

    truncated="$TEST_ROOT/truncated.png"
    cp "$valid" "$truncated"
    truncate -s -12 "$truncated"
    run_compose --boot-background "$truncated"
    [ "$status" -ne 0 ]
    assert_output_contains 'not a supported PNG'

    ln -s "$valid" "$TEST_ROOT/background-link.png"
    run_compose --boot-background "$TEST_ROOT/background-link.png"
    [ "$status" -ne 0 ]
    assert_output_contains 'must not be a symbolic link'

    XORRISO_TAMPER_EXTRACT=/minios/boot/bootlogo791.png \
        run_compose --boot-background "$valid"
    [ "$status" -ne 0 ]
    assert_output_contains 'customization bytes or digest report failed verification'
    [ ! -e "$OUTPUT" ]
}

@test "project overlay snapshots safe files and emits a verified dynamic report" {
    overlay="$TEST_ROOT/project overlay"
    mks_state="$TEST_ROOT/overlay mks state"
    mkdir -p "$overlay/etc" "$overlay/usr/bin" "$overlay/empty"
    write_file "$overlay/etc/application.conf" configured
    write_file "$overlay/usr/bin/image-tool" executable
    chmod 0755 "$overlay/usr/bin/image-tool"
    ln -s ../usr/bin/image-tool "$overlay/etc/tool-link"
    write_file "$SOURCE/image-customization.json" '{"attacker":true}'

    pushd "$TEST_ROOT" >/dev/null
    MKSQUASHFS_STATE="$mks_state" run_compose --overlay-directory "$overlay"
    popd >/dev/null

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    assert_output_contains 'P:customize'
    [ "$(<"$STATE/image-overlay.destination")" = minios/02-image-overlay.sb ]
    [ "$(<"$mks_state/tree/etc/application.conf")" = configured ]
    [ "$(<"$mks_state/tree/usr/bin/image-tool")" = executable ]
    [ "$(readlink "$mks_state/tree/etc/tool-link")" = ../usr/bin/image-tool ]
    grep -q '^mksquashfs:' "$TOOL_EUID_LOG"

    run python3 -c '
import json, sys
report = json.load(open(sys.argv[1], encoding="utf-8"))
assert report["product_kind"] == "minios-image-customization"
assert report["schema_version"] == 1
assert report["boot"] == {"background": None, "configs": [], "default_boot": None,
                           "kernel_args": None, "timeout_seconds": None}
overlay = report["overlay"]
assert overlay["target"] == "minios/02-image-overlay.sb"
assert overlay["module_order"] == 2
assert overlay["size"] > 0
assert len(overlay["sha256"]) == 64
assert len(overlay["input_tree_fingerprint"]) == 64
assert overlay["entry_count"] == 8
' "$STATE/image-customization.json"
    [ "$status" -eq 0 ]
    [[ $(<"$STATE/image-customization.json") != *attacker* ]]
}

@test "overlay builds from an unrelated private working directory" {
    overlay="$TEST_ROOT/portable overlay"
    mkdir -p "$overlay/etc"
    write_file "$overlay/etc/portable.conf" portable

    private_cwd="$TEST_ROOT/private-job-dir"
    mkdir -p "$private_cwd"

    pushd "$private_cwd" >/dev/null
    run_compose --overlay-directory "$overlay"
    popd >/dev/null

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    assert_output_contains 'P:customize'
    [ "$(<"$STATE/image-overlay.destination")" = minios/02-image-overlay.sb ]
}

@test "overlay plus session capture receives consecutive last-load module orders" {
    overlay="$TEST_ROOT/combined overlay"
    mkdir -p "$overlay/etc"
    write_file "$overlay/etc/combined.conf" combined

    pushd "$TEST_ROOT" >/dev/null
    run_compose --overlay-directory "$overlay" --capture-changes exact
    popd >/dev/null

    [ "$status" -eq 0 ]
    [ "$(<"$STATE/image-overlay.destination")" = minios/02-image-overlay.sb ]
    [ "$(<"$STATE/session-capture.destination")" = minios/03-session-changes.sb ]
    [[ $output == *$'P:customize\n'*$'P:capture\n'* ]]
    run python3 -c '
import json, sys
custom = json.load(open(sys.argv[1], encoding="utf-8"))
capture = json.load(open(sys.argv[2], encoding="utf-8"))
assert custom["overlay"]["module_order"] == 2
assert capture["module_order"] == 3
' "$STATE/image-customization.json" "$STATE/session-capture.json"
    [ "$status" -eq 0 ]
}

@test "overlay rejects escaping links special objects directory symlinks and exhausted order" {
    overlay="$TEST_ROOT/unsafe overlay"
    mkdir "$overlay"
    pushd "$TEST_ROOT" >/dev/null

    ln -s /etc/passwd "$overlay/absolute-link"
    run_compose --overlay-directory "$overlay"
    [ "$status" -ne 0 ]
    assert_output_contains 'could not be snapshotted safely'
    rm "$overlay/absolute-link"

    ln -s ../../outside "$overlay/escaping-link"
    run_compose --overlay-directory "$overlay"
    [ "$status" -ne 0 ]
    assert_output_contains 'could not be snapshotted safely'
    rm "$overlay/escaping-link"

    mkfifo "$overlay/unsafe-fifo"
    run_compose --overlay-directory "$overlay"
    [ "$status" -ne 0 ]
    assert_output_contains 'could not be snapshotted safely'
    rm "$overlay/unsafe-fifo"

    ln -s "$overlay" "$TEST_ROOT/overlay-link"
    run_compose --overlay-directory "$TEST_ROOT/overlay-link"
    [ "$status" -ne 0 ]
    assert_output_contains 'readable real directory'

    write_file "$SOURCE/999999-late.sb" late
    run_compose --overlay-directory "$overlay"
    [ "$status" -eq 3 ]
    assert_output_contains 'No safe numeric order remains'
    [ ! -e "$OUTPUT" ]
    popd >/dev/null
}

@test "overlay snapshot detects concurrent input mutation and removes private output" {
    overlay="$TEST_ROOT/mutating overlay"
    pause="$TEST_ROOT/overlay mutation pause"
    log="$TEST_ROOT/overlay-mutation.log"
    mkdir "$overlay"
    write_file "$overlay/value" before

    COMPOSE_TEST_OVERLAY_PAUSE="$pause" start_overlay_compose "$log" \
        --overlay-directory "$overlay"
    script_pid=$STARTED_COMPOSE_PID
    for _ in {1..500}; do
        [[ -e $pause.ready ]] && break
        sleep 0.02
    done
    [ -e "$pause.ready" ]
    write_file "$overlay/value" after
    : >"$pause.continue"
    set +e
    wait "$script_pid"
    result=$?
    set -e

    [ "$result" -ne 0 ]
    grep -q 'could not be snapshotted safely' "$log"
    [ ! -e "$OUTPUT" ]
    shopt -s nullglob dotglob
    leftovers=("$TEMP_ROOT"/*)
    [ "${#leftovers[@]}" -eq 0 ]
}

@test "overlay SquashFS must exactly represent its captured manifest" {
    overlay="$TEST_ROOT/manifest overlay"
    mkdir -p "$overlay/etc"
    write_file "$overlay/etc/value" trusted
    local mutation

    pushd "$TEST_ROOT" >/dev/null
    for mutation in extra:unexpected mutate:etc/value remove:etc/value; do
        UNSQUASHFS_TAMPER_TREE=$mutation run_compose --overlay-directory "$overlay"
        [ "$status" -ne 0 ]
        assert_output_contains 'does not match the captured input manifest'
        [ ! -e "$OUTPUT" ]
    done
    popd >/dev/null
}

@test "TERM stops stubborn overlay mksquashfs descendants and cleans the build" {
    overlay="$TEST_ROOT/cancel overlay"
    started="$TEST_ROOT/overlay-mksquashfs.started"
    log="$TEST_ROOT/overlay-cancel.log"
    mkdir "$overlay"
    write_file "$overlay/value" value

    MKSQUASHFS_SLEEP=true MKSQUASHFS_SLEEP_MARKER="$started" \
        MKSQUASHFS_STUBBORN=true start_overlay_compose "$log" \
        --overlay-directory "$overlay"
    script_pid=$STARTED_COMPOSE_PID
    for _ in {1..500}; do
        [[ -e $started ]] && break
        sleep 0.02
    done
    [ -e "$started" ]
    mapfile -t child_pids <"$started"
    [ "${#child_pids[@]}" -eq 2 ]
    kill -TERM "$script_pid"
    set +e
    wait "$script_pid"
    result=$?
    set -e

    [ "$result" -eq 130 ]
    grep -Fqx 'P:customize' "$log"
    for child_pid in "${child_pids[@]}"; do
        assert_process_gone "$child_pid"
    done
    [ ! -e "$OUTPUT" ]
    shopt -s nullglob dotglob
    leftovers=("$TEMP_ROOT"/*)
    [ "${#leftovers[@]}" -eq 0 ]
}

@test "tampered customization report boot config and overlay module fail verification" {
    prepare_custom_boot_fixture
    overlay="$TEST_ROOT/tamper overlay"
    mkdir "$overlay"
    write_file "$overlay/value" trusted
    local embedded_path
    local -a embedded_paths=(
        /minios/image-customization.json
        /minios/boot/grub/main.cfg
        /minios/02-image-overlay.sb
    )

    pushd "$TEST_ROOT" >/dev/null
    for embedded_path in "${embedded_paths[@]}"; do
        XORRISO_TAMPER_EXTRACT="$embedded_path" run_compose \
            --default-boot fresh --overlay-directory "$overlay"
        [ "$status" -ne 0 ]
        assert_output_contains 'customization bytes or digest report failed verification'
        [ ! -e "$OUTPUT" ]
    done
    popd >/dev/null
}

@test "post-report overlay mutation cannot update both generated and embedded identities" {
    overlay="$TEST_ROOT/post-report overlay"
    mkdir "$overlay"
    write_file "$overlay/value" trusted

    pushd "$TEST_ROOT" >/dev/null
    XORRISO_MUTATE_GRAFT=minios/02-image-overlay.sb \
        run_compose --overlay-directory "$overlay"
    popd >/dev/null

    [ "$status" -ne 0 ]
    assert_output_contains 'customization bytes or digest report failed verification'
    [ ! -e "$OUTPUT" ]
}

@test "an installed-style minios-image-compose cannot enable source test command overrides" {
    installed_root="$TEST_ROOT/installed tree"
    installed_script="$installed_root/bin/minios-image-compose"
    mkdir -p "${installed_script%/*}"
    cp -- "$COMPOSE" "$installed_script"
    chmod 0755 "$installed_script"

    run env \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 \
        MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        COMPOSE_TEST_SAVECHANGES="$CAPTURE_STUB" \
        COMPOSE_TEST_PKEXEC="$PKEXEC_STUB" \
        COMPOSE_TEST_MKSQUASHFS="$OVERLAY_MKS_STUB" \
        "$installed_script" --source "$SOURCE" --config "$CONFIG" \
        --name "$OUTPUT" --capture-changes exact
    [ "$status" -ne 0 ]
    assert_output_contains 'Source-test overrides are unavailable'
    [ ! -e "$CAPTURE_STATE/args" ]
    [ ! -e "$OUTPUT" ]
}

@test "capture elevates only savechanges and keeps ISO phases at the caller EUID" {
    run_compose --capture-changes clean

    [ "$status" -eq 0 ]
    mapfile -d '' -t elevated_arguments <"$PKEXEC_STATE/args"
    [ "${elevated_arguments[0]}" = "$CAPTURE_STUB" ]
    [ "$(<"$PKEXEC_STATE/euid")" -eq "$EUID" ]
    while IFS= read -r observed_euid; do
        [ "$observed_euid" -eq "$EUID" ]
    done <"$STATE/euids"
    while IFS=: read -r _tool observed_euid; do
        [ "$observed_euid" -eq "$EUID" ]
    done <"$TOOL_EUID_LOG"
    assert_output_contains 'P:persistence'
    assert_output_contains 'P:iso-write'
    assert_output_contains 'P:verify'
}

@test "selected capture is hashed reported grafted top-level and phase-transparent" {
    selection_secret='home/private-selection-marker-do-not-log'
    write_file "$SESSION_SELECTION" "{\"product_kind\":\"minios-session-selection\",\"schema_version\":1,\"include_paths\":[\"$selection_secret\"],\"exclude_paths\":[]}"
    expected_selection_hash=$(sha256sum "$SESSION_SELECTION")
    expected_selection_hash=${expected_selection_hash%% *}

    run_compose --manifest "$MANIFEST" --capture-changes=selected \
        --capture-selection="$SESSION_SELECTION" --capture-compression=xz

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    assert_output_contains 'P:capture'
    for phase_id in capture-inventory capture-copy capture-compress capture-complete; do
        assert_output_contains "P:$phase_id"
    done
    assert_output_contains 'Session capture module target: minios/02-session-changes.sb'
    assert_output_contains 'Session capture union backend: overlayfs'
    assert_output_contains 'Session capture module order: 2'
    assert_output_contains 'Session capture module SHA256:'
    [[ $output != *"$selection_secret"* ]]
    grep -Fqx '/minios/02-session-changes.sb' "$STATE/tree"
    grep -Fqx '/minios/session-capture.json' "$STATE/tree"
    [ "$(<"$STATE/session-capture.size")" -gt 0 ]
    assert_capture_arg_pair --profile selected
    assert_capture_arg_pair --comp xz

    mapfile -d '' -t capture_arguments <"$CAPTURE_STATE/args"
    [[ ${capture_arguments[${#capture_arguments[@]}-1]} == */02-session-changes.sb ]]
    selection_copy=""
    capture_work_parent=""
    for index in "${!capture_arguments[@]}"; do
        if [[ ${capture_arguments[$index]} == --selection ]]; then
            selection_copy=${capture_arguments[$((index + 1))]}
        elif [[ ${capture_arguments[$index]} == --work-parent ]]; then
            capture_work_parent=${capture_arguments[$((index + 1))]}
        fi
    done
    [[ $selection_copy == */session-selection.json ]]
    [ -n "$capture_work_parent" ]
    [ "${capture_arguments[${#capture_arguments[@]}-1]%/*}" = "$capture_work_parent" ]

    run python3 -c '
import json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    value = json.load(stream)
assert value["product_kind"] == "minios-session-capture-report"
assert value["schema_version"] == 3
assert value["profile"] == "selected"
assert value["union_backend"] == "overlayfs"
assert value["boot_id"] == "11111111-2222-3333-4444-555555555555"
assert len(value["base_module_fingerprint"]) == 64
assert value["module_order"] == 2
assert value["module"]["target"] == "minios/02-session-changes.sb"
assert value["module"]["size"] > 0
assert len(value["module"]["sha256"]) == 64
assert value["selection_sha256"] == sys.argv[2]
' "$STATE/session-capture.json" "$expected_selection_hash"
    [ "$status" -eq 0 ]
    [[ $(<"$STATE/session-capture.json") != *"$selection_secret"* ]]
    [ "$(<"$MANIFEST")" = '{"schema_version":1}' ]
}

@test "explicit capture source requires and validates running base module binding" {
    SAVECHANGES_STUB_BASE_FINGERPRINT=$(printf '%064d' 1) run_compose --capture-changes exact
    [ "$status" -ne 0 ]
    assert_output_contains 'running base modules do not match the ISO source'
    [ ! -e "$OUTPUT" ]

    SAVECHANGES_STUB_BASE_FINGERPRINT=none run_compose --capture-changes exact
    [ "$status" -ne 0 ]
    assert_output_contains 'explicit ISO source cannot be bound'
    [ ! -e "$OUTPUT" ]
}

@test "capture rejects malformed additive sizing footprint and required identity metadata" {
    local metadata_mode
    local -a metadata_modes=(
        module-size module-digest entry-count-type uncompressed-size-type
        footprint-schema-type footprint-size footprint-field
    )
    for metadata_mode in "${metadata_modes[@]}"; do
        SAVECHANGES_STUB_METADATA_MODE=$metadata_mode \
            run_compose --capture-changes exact
        [ "$status" -ne 0 ]
        assert_output_contains 'Cannot validate privileged capture metadata or create report'
        [ ! -e "$OUTPUT" ]
    done
}

@test "capture order is dynamic and sorts after 10 99 and 100-plus modules" {
    write_file "$SOURCE/10-application.sb" ten
    write_file "$SOURCE/99-late.sb" ninety-nine
    write_file "$SOURCE/modules/100-extra.sb" one-hundred
    run_compose --capture-changes exact
    [ "$status" -eq 0 ]
    grep -Fqx '/minios/101-session-changes.sb' "$STATE/tree"
    [ "$(<"$STATE/session-capture.destination")" = minios/101-session-changes.sb ]
    run python3 -c '
import json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    report = json.load(stream)
assert report["module_order"] == 101
assert report["module"]["target"] == "minios/101-session-changes.sb"
' "$STATE/session-capture.json"
    [ "$status" -eq 0 ]

    rm "$OUTPUT"
    write_file "$SOURCE/999999-blocker.sb" blocker
    run_compose --capture-changes exact
    [ "$status" -eq 3 ]
    assert_output_contains 'No safe numeric order remains'
}

@test "invalid capture output and missing ISO capture graft fail closed" {
    SAVECHANGES_STUB_MODE=empty run_compose --capture-changes clean
    [ "$status" -ne 0 ]
    assert_output_contains 'did not create a nonempty regular capture module'
    [ ! -e "$OUTPUT" ]

    SAVECHANGES_STUB_MODE=success
    XORRISO_OMIT_DEST=minios/02-session-changes.sb run_compose --capture-changes clean
    [ "$status" -ne 0 ]
    assert_output_contains 'missing grafted path: minios/02-session-changes.sb'
    [ ! -e "$OUTPUT" ]
}

@test "tampered embedded capture report module and manifest bytes fail verification" {
    local embedded_path
    local -a embedded_paths=(
        /minios/session-capture.json
        /minios/02-session-changes.sb
        /minios/build-manifest.json
    )

    for embedded_path in "${embedded_paths[@]}"; do
        XORRISO_TAMPER_EXTRACT="$embedded_path" run_compose \
            --manifest "$MANIFEST" --capture-changes exact
        [ "$status" -ne 0 ]
        assert_output_contains 'Embedded capture bytes or digest report failed verification'
        [ ! -e "$OUTPUT" ]
    done
}

@test "real savechanges and SquashFS tools flow through capture report and extraction" {
    real_mksquashfs=$(PATH="$SYSTEM_PATH" command -v mksquashfs) ||
        skip 'mksquashfs is not installed'
    real_unsquashfs=$(PATH="$SYSTEM_PATH" command -v unsquashfs) ||
        skip 'unsquashfs is not installed'
    capture_tools="$TEST_ROOT/real capture tools"
    capture_source="$TEST_ROOT/real savechanges source"
    changes="$TEST_ROOT/real writable changes"
    mkdir -p "$capture_tools" "$capture_source/bin" "$capture_source/lib" \
        "$capture_source/tests"
    write_file "$changes/etc/default/integrated-value" integrated-capture
    CAPTURE_STUB="$capture_source/bin/savechanges"
    real_savechanges="${COMPOSE_REAL_SAVECHANGES:-}"
    [ -n "$real_savechanges" ] ||
        real_savechanges=$(PATH="$SYSTEM_PATH" command -v savechanges 2>/dev/null) ||
        true
    [ -n "$real_savechanges" ] && [ -f "$real_savechanges" ] ||
        real_savechanges="$BATS_TEST_DIRNAME/../../../minios-tools/bin/savechanges"
    [ -f "$real_savechanges" ] || skip 'savechanges is not available'
    cp -- "$real_savechanges" "$CAPTURE_STUB"
    real_savechanges_engine="${real_savechanges%/*}/../lib/minios_savechanges_engine.py"
    if [ -f "$real_savechanges_engine" ]; then
        cp -- "$real_savechanges_engine" \
            "$capture_source/lib/minios_savechanges_engine.py"
    fi
    cp -- "$BATS_TEST_DIRNAME/.source-test-context" "$capture_source/tests/.source-test-context"
    cp -- "$real_mksquashfs" "$capture_tools/mksquashfs"
    cp -- "$real_unsquashfs" "$capture_tools/unsquashfs"
    chmod 0755 "$CAPTURE_STUB" "$capture_tools/mksquashfs" "$capture_tools/unsquashfs"
    capture_mountinfo="$TEST_ROOT/real capture mountinfo"
    capture_cmdline="$TEST_ROOT/real capture cmdline"
    capture_boot_id="$TEST_ROOT/real capture boot-id"
    escaped_changes=${changes// /\\040}
    printf '24 1 0:1 / / rw - overlay overlay rw,lowerdir=/lower/01-kernel-amd64.sb:/lower/00-core-amd64.sb,upperdir=%s,workdir=/work\n' \
        "$escaped_changes" >"$capture_mountinfo"
    printf '%s\n' 'BOOT_IMAGE=/minios/boot/vmlinuz union=aufs' >"$capture_cmdline"
    printf '%s\n' '11111111-2222-3333-4444-555555555555' >"$capture_boot_id"

    COMPOSE_TEST_CHANGES_ROOT="$changes" \
        MINIOS_TOOLS_TEST_MKSQUASHFS="$capture_tools/mksquashfs" \
        MINIOS_TOOLS_TEST_UNSQUASHFS="$capture_tools/unsquashfs" \
        MINIOS_TOOLS_TEST_MOUNTINFO="$capture_mountinfo" \
        MINIOS_TOOLS_TEST_CMDLINE="$capture_cmdline" \
        MINIOS_TOOLS_TEST_BOOT_ID="$capture_boot_id" \
        MINIOS_TOOLS_TEST_RUNNING_SOURCE="$SOURCE" \
        run_compose --capture-changes exact

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    [ -s "$STATE/session-capture.sb" ]
    extracted="$TEST_ROOT/extracted capture"
    run "$real_unsquashfs" -d "$extracted" "$STATE/session-capture.sb"
    [ "$status" -eq 0 ]
    [ "$(<"$extracted/etc/default/integrated-value")" = integrated-capture ]
}

@test "real mksquashfs conditionally creates a readable rootless image overlay" {
    real_mksquashfs=$(PATH="$SYSTEM_PATH" command -v mksquashfs) ||
        skip 'mksquashfs is not installed'
    real_unsquashfs=$(PATH="$SYSTEM_PATH" command -v unsquashfs) ||
        skip 'unsquashfs is not installed'
    cp -- "$real_mksquashfs" "$OVERLAY_MKS_STUB"
    chmod 0755 "$OVERLAY_MKS_STUB"
    overlay="$TEST_ROOT/real overlay"
    mkdir -p "$overlay/etc" "$overlay/usr/bin"
    write_file "$overlay/etc/real.conf" real-overlay
    write_file "$overlay/usr/bin/real-tool" executable
    chmod 0755 "$overlay/usr/bin/real-tool"
    chmod 0644 "$overlay/etc/real.conf"
    ln -s ../usr/bin/real-tool "$overlay/etc/real-tool-link"
    touch -d '@1700000100' "$overlay/etc/real.conf" "$overlay/usr/bin/real-tool"
    expected_config_hash=$(sha256sum "$overlay/etc/real.conf")
    expected_config_hash=${expected_config_hash%% *}

    pushd "$TEST_ROOT" >/dev/null
    run_compose --overlay-directory "$overlay"
    popd >/dev/null

    [ "$status" -eq 0 ]
    [ -s "$STATE/image-overlay.sb" ]
    run "$real_unsquashfs" -s "$STATE/image-overlay.sb"
    [ "$status" -eq 0 ]
    extracted="$TEST_ROOT/real overlay extracted"
    run "$real_unsquashfs" -d "$extracted" "$STATE/image-overlay.sb"
    [ "$status" -eq 0 ]
    [ "$(<"$extracted/etc/real.conf")" = real-overlay ]
    [ "$(stat -c '%a' "$extracted/etc/real.conf")" = 644 ]
    [ -x "$extracted/usr/bin/real-tool" ]
    [ "$(stat -c '%a' "$extracted/usr/bin/real-tool")" = 755 ]
    [ "$(stat -c '%Y' "$extracted/etc/real.conf")" = 1700000100 ]
    [ -L "$extracted/etc/real-tool-link" ]
    [ "$(readlink "$extracted/etc/real-tool-link")" = ../usr/bin/real-tool ]
    extracted_config_hash=$(sha256sum "$extracted/etc/real.conf")
    [ "${extracted_config_hash%% *}" = "$expected_config_hash" ]
}

@test "nested cancellation marker stops a root capture helper across the UID boundary" {
    (( EUID != 0 )) || skip 'requires an unprivileged minios-image-compose parent'
    [[ -x /usr/bin/sudo ]] || skip 'sudo is unavailable'
    /usr/bin/sudo -n true >/dev/null 2>&1 || skip 'passwordless sudo is unavailable'
    log="$TEST_ROOT/root-capture-cancel.log"

    set +e
    env \
        PATH="$STUBS:$SYSTEM_PATH" \
        TMPDIR="$TEMP_ROOT" \
        XORRISO_STATE="$STATE" \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 \
        MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        COMPOSE_TEST_SAVECHANGES="$CAPTURE_STUB" \
        COMPOSE_TEST_PKEXEC="$PKEXEC_STUB" \
        PKEXEC_STUB_STATE="$PKEXEC_STATE" \
        PKEXEC_STUB_ROOT=true \
        SAVECHANGES_STUB_STATE="$CAPTURE_STATE" \
        SAVECHANGES_STUB_MODE=root-stubborn \
        SAVECHANGES_STUB_SOURCE="$SOURCE" \
        NO_COLOR=1 \
        "$COMPOSE" --source "$SOURCE" --config "$CONFIG" --name "$OUTPUT" \
        --capture-changes clean >"$log" 2>&1 &
    script_pid=$!
    for _ in {1..500}; do
        [[ -e $CAPTURE_STATE/root.started ]] && break
        sleep 0.02
    done
    [ -e "$CAPTURE_STATE/root.started" ]
    mapfile -t root_pids <"$CAPTURE_STATE/root.started"
    [ "${#root_pids[@]}" -eq 2 ]
    [ "$(stat -c '%u' "/proc/${root_pids[0]}")" -eq 0 ]
    if kill -TERM "${root_pids[0]}" 2>/dev/null; then
        false
    fi

    mapfile -d '' -t capture_arguments <"$CAPTURE_STATE/args"
    cancel_file=""
    for index in "${!capture_arguments[@]}"; do
        if [[ ${capture_arguments[$index]} == --cancel-file ]]; then
            cancel_file=${capture_arguments[$((index + 1))]}
        fi
    done
    [[ $cancel_file == "$TEMP_ROOT"/minios-image-compose.*/capture.cancel ]]
    [ "$(stat -c '%a' "${cancel_file%/*}")" = 700 ]
    [ "$(stat -c '%u' "${cancel_file%/*}")" -eq "$EUID" ]
    [ ! -e "$cancel_file" ]

    kill -TERM "$script_pid"
    result=0
    wait "$script_pid" || result=$?
    set -e

    [ "$result" -eq 130 ]
    grep -Fqx 'P:cancelled' "$log"
    [[ $(<"$log") != *"$cancel_file"* ]]
    for root_pid in "${root_pids[@]}"; do
        assert_process_gone "$root_pid"
    done
    [ ! -e "$OUTPUT" ]
    [ ! -e "$cancel_file" ]
    shopt -s nullglob dotglob
    leftovers=("$TEMP_ROOT"/*)
    [ "${#leftovers[@]}" -eq 0 ]
}

@test "TERM escalates for a stubborn writer and cleanup exits 130 without partial files" {
    log="$TEST_ROOT/signal.log"
    set +e
    env \
        PATH="$STUBS:$SYSTEM_PATH" \
        TMPDIR="$TEMP_ROOT" \
        XORRISO_STATE="$STATE" \
        XORRISO_BUILD_MODE=stubborn \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 \
        MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        NO_COLOR=1 \
        "$COMPOSE" --source "$SOURCE" --config "$CONFIG" --name "$OUTPUT" \
        >"$log" 2>&1 &
    script_pid=$!
    for _ in {1..100}; do
        [[ -e $STATE/build.started ]] && break
        sleep 0.05
    done
    [ -e "$STATE/build.started" ]
    mapfile -t child_pids <"$STATE/build.started"
    [ "${#child_pids[@]}" -eq 2 ]
    shopt -s nullglob
    active_temp_dirs=("$TEMP_ROOT"/minios-image-compose.*)
    [ "${#active_temp_dirs[@]}" -eq 1 ]
    [ "$(stat -c '%a' "${active_temp_dirs[0]}")" = 700 ]
    kill -TERM "$script_pid"
    wait "$script_pid"
    result=$?
    set -e

    [ "$result" -eq 130 ]
    for child_pid in "${child_pids[@]}"; do
        assert_process_gone "$child_pid"
    done
    [ ! -e "$OUTPUT" ]
    shopt -s nullglob dotglob
    leftovers=("$TEMP_ROOT"/*)
    [ "${#leftovers[@]}" -eq 0 ]
}

@test "a writer leader exit cannot orphan its process group" {
    XORRISO_BUILD_MODE=leader-exit run_compose

    [ "$status" -ne 0 ]
    assert_output_contains 'descendant processes remained'
    mapfile -t child_pids <"$STATE/build.started"
    [ "${#child_pids[@]}" -eq 2 ]
    for child_pid in "${child_pids[@]}"; do
        assert_process_gone "$child_pid"
    done
    [ ! -e "$OUTPUT" ]
    shopt -s nullglob dotglob
    leftovers=("$TEMP_ROOT"/*)
    [ "${#leftovers[@]}" -eq 0 ]
}

@test "routine real no-custom ISO preserves source metadata and extracted Rock Ridge modes" {
    (( EUID != 0 )) || skip 'rootless metadata integration requires an unprivileged caller'
    prepare_real_iso_fixture
    source_before=$(stat -c '%a:%Y:%d:%i:%h' \
        "$SOURCE/metadata/executable" "$SOURCE/metadata/plain" \
        "$SOURCE/metadata/plain-link" "$SOURCE/metadata/large.bin")
    source_hash_before=$(sha256sum "$SOURCE/metadata/executable" "$SOURCE/metadata/plain" \
        "$SOURCE/metadata/large.bin")

    run env PATH="$REAL_XORRISO_TOOLS:$SYSTEM_PATH" TMPDIR="$TEMP_ROOT" \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        REAL_XORRISO="$REAL_XORRISO" REAL_XORRISO_STATE="$REAL_XORRISO_STATE" \
        REAL_XORRISO_SOURCE_FILE="$SOURCE/metadata/large.bin" \
        LC_ALL=C.UTF-8 LANG=C.UTF-8 NO_COLOR=1 \
        "$COMPOSE" --source "$SOURCE" --config "$CONFIG" --name "$OUTPUT"

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    [ -e "$REAL_XORRISO_STATE/snapshot-inplace" ]
    [ "$(stat -c '%a:%Y:%d:%i:%h' \
        "$SOURCE/metadata/executable" "$SOURCE/metadata/plain" \
        "$SOURCE/metadata/plain-link" "$SOURCE/metadata/large.bin")" = "$source_before" ]
    [ "$(sha256sum "$SOURCE/metadata/executable" "$SOURCE/metadata/plain" \
        "$SOURCE/metadata/large.bin")" = "$source_hash_before" ]

    extracted="$TEST_ROOT/real extracted metadata"
    run "$REAL_XORRISO" -no_rc -osirrox on -indev "$OUTPUT" \
        -extract /minios/metadata "$extracted" -end
    [ "$status" -eq 0 ]
    [ "$(stat -c '%a' "$extracted/executable")" = 755 ]
    [ "$(stat -c '%a' "$extracted/plain")" = 644 ]
    [ "$(stat -c '%a' "$extracted/large.bin")" = 644 ]
    [ -L "$extracted/plain-link" ]
    [ "$(stat -c '%a' "$extracted/plain-link")" = 777 ]
    [ "$(readlink "$extracted/plain-link")" = plain ]
    [ "$(stat -c '%Y' "$extracted/executable")" = 1700000000 ]
    [ "$(stat -c '%Y' "$extracted/plain")" = 1700000000 ]
}

@test "real xorriso preserves the MiniOS chainloader while transforming authoritative GRUB" {
    (( EUID != 0 )) || skip 'rootless chainloader integration requires an unprivileged caller'
    prepare_real_iso_fixture
    prepare_syslinux_grub_fixture
    kernel_text='audit=1 real_chainloader=verified'

    run env PATH="$REAL_XORRISO_TOOLS:$SYSTEM_PATH" TMPDIR="$TEMP_ROOT" \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        REAL_XORRISO="$REAL_XORRISO" REAL_XORRISO_STATE="$REAL_XORRISO_STATE" \
        LC_ALL=C.UTF-8 LANG=C.UTF-8 NO_COLOR=1 \
        "$COMPOSE" --source "$SOURCE" --config "$CONFIG" --name "$OUTPUT" \
        --boot-timeout 4 --default-boot fresh --kernel-args "$kernel_text"

    [ "$status" -eq 0 ]
    [ -s "$OUTPUT" ]
    extracted="$TEST_ROOT/real chainloader extraction"
    mkdir "$extracted"
    run "$REAL_XORRISO" -no_rc -osirrox on -indev "$OUTPUT" \
        -extract /minios/boot/grub/main.cfg "$extracted/main.cfg" \
        -extract /minios/boot/syslinux/syslinux.cfg "$extracted/syslinux.cfg" -end
    [ "$status" -eq 0 ]
    grep -Fqx 'set timeout=4' "$extracted/main.cfg"
    grep -Fqx 'set default=3' "$extracted/main.cfg"
    [ "$(grep -Fc " $kernel_text" "$extracted/main.cfg")" -eq 5 ]
    grep -Fqx 'TIMEOUT 1' "$extracted/syslinux.cfg"
    grep -Fqx 'LINUX /minios/boot/grub/i386-pc/lnxboot.img' "$extracted/syslinux.cfg"
    grep -Fqx 'INITRD /minios/boot/grub/i386-pc/core.img' "$extracted/syslinux.cfg"
    [ "$(grep -Fc "$kernel_text" "$extracted/syslinux.cfg")" -eq 0 ]
}

@test "real xorriso detects overlay mutation after report generation" {
    (( EUID != 0 )) || skip 'rootless overlay integration requires an unprivileged caller'
    prepare_real_iso_fixture
    overlay="$TEST_ROOT/real mutation overlay"
    mkdir "$overlay"
    write_file "$overlay/value" trusted

    pushd "$TEST_ROOT" >/dev/null
    run env PATH="$REAL_XORRISO_TOOLS:$SYSTEM_PATH" TMPDIR="$TEMP_ROOT" \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        REAL_XORRISO="$REAL_XORRISO" REAL_XORRISO_STATE="$REAL_XORRISO_STATE" \
        REAL_XORRISO_MUTATE_OVERLAY=true LC_ALL=C.UTF-8 LANG=C.UTF-8 NO_COLOR=1 \
        "$COMPOSE" --source "$SOURCE" --config "$CONFIG" --name "$OUTPUT" \
        --overlay-directory "$overlay"
    popd >/dev/null

    [ "$status" -ne 0 ]
    [ -e "$REAL_XORRISO_STATE/overlay-mutated" ]
    assert_output_contains 'customization bytes or digest report failed verification'
    [ ! -e "$OUTPUT" ]
}

@test "real xorriso rejects independently tampered customization report sections" {
    (( EUID != 0 )) || skip 'rootless customization-attestation integration requires an unprivileged caller'
    prepare_real_iso_fixture
    prepare_custom_boot_fixture
    background="$TEST_ROOT/real report background.png"
    overlay="$TEST_ROOT/real report overlay"
    create_test_png "$background" 1024 768
    mkdir "$overlay"
    write_file "$overlay/value" trusted
    local mutation
    local -a mutations=(identity duplicate nonfinite boot configs background overlay presence)

    pushd "$TEST_ROOT" >/dev/null
    for mutation in "${mutations[@]}"; do
        rm -f "$REAL_XORRISO_STATE/report-mutated"
        run env PATH="$REAL_XORRISO_TOOLS:$SYSTEM_PATH" TMPDIR="$TEMP_ROOT" \
            MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
            REAL_XORRISO="$REAL_XORRISO" REAL_XORRISO_STATE="$REAL_XORRISO_STATE" \
            REAL_XORRISO_MUTATE_REPORT="$mutation" \
            LC_ALL=C.UTF-8 LANG=C.UTF-8 NO_COLOR=1 \
            "$COMPOSE" --source "$SOURCE" --config "$CONFIG" --name "$OUTPUT" \
            --boot-timeout 4 --default-boot fresh --kernel-args 'audit=1' \
            --boot-background "$background" --overlay-directory "$overlay"
        [ "$status" -ne 0 ]
        [ "$(<"$REAL_XORRISO_STATE/report-mutated")" = "$mutation" ]
        assert_output_contains 'customization bytes or digest report failed verification'
        [ ! -e "$OUTPUT" ]
    done
    popd >/dev/null
}

@test "real xorriso cannot coordinate overlay bytes and report digest mutation" {
    (( EUID != 0 )) || skip 'rootless customization-attestation integration requires an unprivileged caller'
    prepare_real_iso_fixture
    overlay="$TEST_ROOT/real coordinated overlay"
    mkdir "$overlay"
    write_file "$overlay/value" trusted

    pushd "$TEST_ROOT" >/dev/null
    run env PATH="$REAL_XORRISO_TOOLS:$SYSTEM_PATH" TMPDIR="$TEMP_ROOT" \
        MINIOS_TOOLS_TEST_ALLOW_NON_ROOT=1 MINIOS_TOOLS_TEST_ROOT="$TEST_ROOT" \
        REAL_XORRISO="$REAL_XORRISO" REAL_XORRISO_STATE="$REAL_XORRISO_STATE" \
        REAL_XORRISO_MUTATE_REPORT=coordinated-overlay \
        LC_ALL=C.UTF-8 LANG=C.UTF-8 NO_COLOR=1 \
        "$COMPOSE" --source "$SOURCE" --config "$CONFIG" --name "$OUTPUT" \
        --overlay-directory "$overlay"
    popd >/dev/null

    [ "$status" -ne 0 ]
    [ -e "$REAL_XORRISO_STATE/overlay-mutated" ]
    [ "$(<"$REAL_XORRISO_STATE/report-mutated")" = coordinated-overlay ]
    assert_output_contains 'customization bytes or digest report failed verification'
    [ ! -e "$OUTPUT" ]
}

@test "real xorriso accepts reserved output and escaped graft pathspecs" {
    real_xorriso=$(PATH="$SYSTEM_PATH" command -v xorriso) ||
        skip 'xorriso is not installed'
    source_file=$'real source/odd [x]*=\\name\tfile'
    destination=$'minios/-odd [x]*=\\name\tfile'
    source_path="$TEST_ROOT/$source_file"
    empty_source="$TEST_ROOT/real empty directory"
    empty_destination='minios/empty target directory'
    image_path="$OUTPUT_DIR/real graft.iso"
    write_file "$source_path" real-data
    mkdir -p "$empty_source"
    : >"$image_path"

    escaped_destination=${destination//\\/\\\\}
    escaped_destination=${escaped_destination//=/\\=}
    escaped_source=${source_path//\\/\\\\}
    escaped_source=${escaped_source//=/\\=}
    escaped_empty_source=${empty_source//\\/\\\\}
    escaped_empty_source=${escaped_empty_source//=/\\=}
    run "$real_xorriso" -no_rc -as mkisofs -volid 'MINIOS LAB' -graft-points \
        "$escaped_destination=$escaped_source" \
        "$empty_destination=$escaped_empty_source" -output "$image_path"
    [ "$status" -eq 0 ]
    [ -s "$image_path" ]

    run "$real_xorriso" -no_rc -indev "$image_path" -pvd_info -sh_style_result on \
        -find / -exec echo -- -end
    [ "$status" -eq 0 ]
    [[ $output == *'Volume Id    : MINIOS LAB'* ]]
    [[ $output == *"/$destination"* ]]
    [[ $output == *"/$empty_destination"* ]]
}

@test "real-tool integration runs only with an explicit source fixture" {
    if [[ ${COMPOSE_RUN_REAL_INTEGRATION:-0} != 1 ||
          -z ${COMPOSE_REAL_SOURCE:-} || -z ${COMPOSE_REAL_CONFIG:-} ]]; then
        skip 'set COMPOSE_RUN_REAL_INTEGRATION=1, COMPOSE_REAL_SOURCE, and COMPOSE_REAL_CONFIG'
    fi

    real_output="$TEST_ROOT/real.iso"
    run env PATH="$SYSTEM_PATH" TMPDIR="$TEMP_ROOT" NO_COLOR=1 \
        "$COMPOSE" --source "$COMPOSE_REAL_SOURCE" \
        --config "$COMPOSE_REAL_CONFIG" --name "$real_output"
    [ "$status" -eq 0 ]
    [ -s "$real_output" ]
}
